[package]
name = "rocal"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
chrono-tz = "0.9.0"
dir = "0.1.2"
dirs = "5.0.1"
icalendar = { version = "0.16.3", features = ["chrono-tz"] }
inquire = { version = "0.7.5", features = ["date"] }
