# Copyright 2023-2024 Hugo Osvaldo Barrera
#
# SPDX-License-Identifier: ISC

image: alpine/edge
packages:
  - cargo
  - rust
  - rustfmt
  - rust-clippy
  - rsync
environment:
  CARGO_TERM_COLOR: always
triggers:
  - action: email
    condition: failure
    to: Hugo Osvaldo Barrera <hugo@whynothugo.nl>
tasks:
  - prepare: |
      cd libdav
      cargo fetch --locked  # make sure lockfile is up to date
  - build: |
      cd libdav
      cargo build
  - lint: |
      cd libdav
      cargo fmt --check
      cargo clippy
  - test: |
      cd libdav
      cargo test  # includes examples and doctests
  - doc: |
      cd libdav
      cargo doc  # fails on broken links
  # TODO: publish docs?
